image: conda/miniconda3

.template_retry:
  retry:
    max: 2
    when: runner_system_failure

conda_build:
  stage: build
  script:
    - conda update --all
    - conda install conda-build git
    - mkdir conda-bld
    - conda build . -c mosaic --output-folder conda-bld/
  extends: .template_retry
  artifacts:
    paths:
      - conda-bld
  only:
    - master
    - develop

coverage:
  stage: test
  script:
  - conda env create -f conda/env.yaml
  - source activate sam_spaghetti
  - python setup.py develop
#  - nosetests -v
  extends: .template_retry
  only:
  - master
  - develop
 
anaconda:
  stage: deploy
  script:
  - conda update --all
  - conda install conda-build anaconda-client
  - conda convert -p osx-64 conda-bld/linux-64/sam_spaghetti-* --output-dir conda-bld/
  - anaconda --token=$ANACONDA_TOKEN --verbose upload conda-bld/linux-64/sam_spaghetti-* --user mosaic
  - anaconda --token=$ANACONDA_TOKEN --verbose upload conda-bld/osx-64/sam_spaghetti-* --user mosaic
  extends: .template_retry
  only:
  - master
  - develop

pages:
  stage: deploy
  script:
  - conda update --all
  - conda env create -f conda/env.yaml
  - source activate sam_spaghetti
  - python setup.py develop
  - conda install -c conda-forge sphinx make jupyter_client nbsphinx
  - ./dowload_sam_data.sh
  - cd doc
  - make html
  - mv build/html ../public
  extends: .template_retry
  artifacts:
    paths:
    - public
  when: manual
  only:
  - master
  - develop
